name: Test

on:
    push:
    pull_request:
    schedule: 
      - cron: '* 12 * * *'


jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@master
          - name: Setup deno
            uses: denolib/setup-deno@master
            with:
              deno-version: v1.x
          - name: Run test
            run: chmod +ux test.sh && ./test.sh