name: Test

on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup deno
        uses: denolib/setup-deno@master
        with:
          deno-version: v1.x
      - name: Run test
        run: chmod +x test.sh && ./test.sh
